# Generated by Django 5.0.6 on 2024-08-28 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("created", models.DateField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("contacto_dueno", models.CharField(max_length=45)),
                ("especie", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("color", models.CharField(max_length=6)),
                ("tamano", models.IntegerField()),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Procedimiento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="web.mascota"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="web.user"
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="web.sala"
                    ),
                ),
            ],
        ),
    ]
